### ISSUE TITLE
Clean installs from repo lead to deprecation warnings in Mongoose

### ISSUE THREAD

**Issue by JacksonBates** [Pairboard/Pairboard#23]
Server is hitting a problem with launching database.

Error log reads:
![image](https://user-images.githubusercontent.com/4337740/31981025-2684c17c-b99c-11e7-9fd4-d3f27c024cb1.png)

**Comment by JacksonBates** [comment]
I think I have fixed this with the latest commit. Just doing a fresh install to test.

**Comment by JacksonBates** [comment]
The real issue was a clash on the ports, but it didn't hurt to fix the deprecation issue either.

**Comment by BenGitter** [comment]
I still get the following warning:
 ```
DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
```

Adding:
```
mongoose.Promise = global.Promise;
```
should fix it.

Also not sure why you would write the result of `mongoose.connect` to a variable?

I think this code should work fine (adding only two lines of code to the initial server.js):
```
mongoose.Promise = global.Promise;   // <- added

mongoose.connect( url, {
  useMongoClient: true,              // <- added
} );

var db = mongoose.connection;
db.on( 'error', console.error.bind( console, 'connection error:' ) );
if ( !process.env.NODE_ENV === 'test' ) {
  db.once( 'open', function () {
    console.log( 'DB Connected' );
  } );
}
```

Or did I just not correctly update after your commit?

**Comment by JacksonBates** [comment]
I was going to open that as a separate issue later. It's only a warning, but better to update it properly.

My initial problem was actually nothing to do with the deprecation problem - it was just a port clash on windows :)

If you want to make a separate issue and fix it with a PR, go ahead :)

Does this mean you're back on board, @BenGitter?

**Comment by JacksonBates** [comment]
Just to clarify - I fixed the useMongoClient requirement, but that led to the mpromise deprecation warning.

I half suspect when we fix the mpromise one, another one will rear its head :)

**Comment by BenGitter** [comment]
I will create an issue for it. 

> Does this mean you're back on board, @BenGitter?

I believe I have not even added one commit so far... But I certainly want to start now 👍

**Comment by JacksonBates** [comment]
IIRC you wrote some of the early tests when it was living in the other two repos :)
