### ISSUE TITLE
Catch mongoose connection error

### ISSUE THREAD

**Issue by BenGitter** [Pairboard/Pairboard#31]
Commit 93cb9216e300183fa9a05acd30f481f2348e60ea does not use a `.catch()` for possible connection errors (try running `node server.js` without mongo running).

I think something like this should work:
```
const promise = mongoose.connect( url, {
  useMongoClient: true,
} );

promise.then( ( db ) => {
  db.on( 'error', console.error.bind( console, 'connection error:' ) );
  if ( !process.env.NODE_ENV === 'test' ) {
    db.once( 'open', function () {
      console.log( 'DB Connected' );
    } );
  }
} )
.catch( err => console.log( err ) );
```

And maybe we can just chain it like this:
```
mongoose.connect( url, {
  useMongoClient: true,
} ).then( ( db ) => {
  ...
} ).catch( ( err ) => {
  ...
} );
```
Instead of having a `promise` variable.

**Comment by JacksonBates** [comment]
Yep - I was hacky and impatient.

**Comment by BenGitter** [comment]
I assumed that `!process.env.NODE_ENV === 'test'` means `process.env.NODE_ENV !== 'test'`
