### ISSUE TITLE
TravisCI tests fail since forks can't read env variables

### ISSUE THREAD

**Issue by JacksonBates** [Pairboard/Pairboard#32]
We need a solution to this, since all builds that don't come from me personally will fail.

Proposals:
Tell trav not to run tests from forks???
Tell trav not to run tests requiring auth (is that possible) from forks
Kill trav
Hand out write access like candy to all contributors???

There must be a simple solution, plenty of repos need GitHub auth and Travis...

**Comment by BenGitter** [comment]
Not a nice solution, but this seems to work: 
```
if ( process.env.NODE_ENV !== 'test' ) require( './authentication' );
```

**Comment by BenGitter** [comment]
Just tested this on my pull request, it now passes the tests.

**Comment by JacksonBates** [comment]
If something falls over later, we'll fix it later!

Good fix :)
