### ISSUE TITLE
Use insertMany in seed file instead of saving one by one

### ISSUE THREAD

**Issue by kevcomedia** [Pairboard/Pairboard#43]
There's the `insertMany` method, which, according to the Mongoose docs, is a fast operation because it sends only one operation to the server. Could be useful if ever seeds or tests need to be added, and looks DRYer overall.

**Comment by JacksonBates** [comment]
Would you like to work on it? Always happy to refactor for better methods.

**Comment by kevcomedia** [comment]
Yeah, let me work on it.
